title: EvWin Flooring
email: everett@evwinflooring.com
description: >- # this means to ignore newlines until "baseurl:"
  Vinyl Flooring and Carpet Installation.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://evwinflooring.com" # the base hostname & protocol for your site, e.g. http://example.com
include:
 - assets
theme: minima
defaults:
  - scope:
      path: "assets/img"
    values:
      image: true